name: 'Genesis Kit Build, Test & Spec Check'
description: 'Builds Genesis kit, runs spec tests, checks for breaking changes, and tests deployment'
author: 'Genesis Community'

inputs:
  kit_name:
    description: 'Name of the Genesis kit'
    required: true
  version_bump:
    description: 'Type of version bump (patch, minor, major)'
    required: false
    default: 'patch'
  debug_mode:
    description: 'Skip testing and just create PR for release'
    required: false
    default: 'false'
  go_version:
    description: 'Go version to use for tests'
    required: false
    default: 'go1.23.5.linux-amd64.tar.gz'
  ginkgo_params:
    description: 'Ginkgo test parameters'
    required: false
    default: '-p'
  deploy_env:
    description: 'Deployment environment for testing'
    required: false
    default: 'ci-vsphere-baseline'
  iaas_provider:
    description: 'Infrastructure type (vsphere, aws, gcp, etc)'
    required: false
    default: 'vsphere'
  release_branch:
    description: 'Branch to create PR against for releases'
    required: false
    default: 'main'
  # Infrastructure credentials
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: false
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: false
  gcp_service_account_key:
    description: 'GCP Service Account Key'
    required: false
  vsphere_username:
    description: 'vSphere Username'
    required: false
  vsphere_password:
    description: 'vSphere Password'
    required: false
  # Genesis/BOSH credentials
  secrets_base:
    description: 'Genesis secrets base'
    required: false
  secrets_token:
    description: 'Genesis secrets token'
    required: false
  secrets_key:
    description: 'Genesis secrets key'
    required: false
  bosh_client:
    description: 'BOSH client'
    required: false
  bosh_client_secret:
    description: 'BOSH client secret'
    required: false
  bosh_environment:
    description: 'BOSH environment'
    required: false
  bosh_ca_cert:
    description: 'BOSH CA certificate'
    required: false
  secrets_seed_data:
    description: 'Seed data for secrets'
    required: false
  github_token:
    description: 'GitHub token for operations'
    required: true

outputs:
  version:
    description: 'The new version number'
    value: ${{ steps.version.outputs.new_version }}
  previous_version:
    description: 'The previous version number'
    value: ${{ steps.version.outputs.previous_version }}
  has_breaking_changes:
    description: 'Whether breaking changes were detected'
    value: ${{ steps.check-breaking.outputs.has_breaking_changes }}
  is_release_commit:
    description: 'Whether the commit message indicates a release'
    value: ${{ steps.check-release-commit.outputs.is_release }}
  release_version:
    description: 'Version to release from commit message'
    value: ${{ steps.check-release-commit.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Setup tools
      shell: bash
      run: |
        echo "::group::Setting up required tools"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/setup-tools.sh
        echo "::endgroup::"

    # VERSION MANAGEMENT
    - name: Get current version
      id: current
      shell: bash
      run: |
        echo "::group::Getting current version"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/get-current-version.sh
        echo "::endgroup::"

    - name: Bump version
      id: version
      shell: bash
      env:
        VERSION_BUMP: ${{ inputs.version_bump }}
        CURRENT_VERSION: ${{ steps.current.outputs.current_version }}
      run: |
        echo "::group::Bumping version from ${{ steps.current.outputs.current_version }}"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/bump-version.sh
        echo "::endgroup::"

    # Check if this is a release commit
    - name: Check for release commit
      id: check-release-commit
      shell: bash
      run: |
        echo "::group::Checking if this is a release commit"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/check-release-commit.sh
        echo "::endgroup::"

    # BUILD KIT (Required even in debug mode)
    - name: Build Kit
      shell: bash
      env:
        GENESIS_SECRETS_BASE: ${{ inputs.secrets_base }}
        GENESIS_SECRETS_TOKEN: ${{ inputs.secrets_token }}
        GENESIS_SECRETS_KEY: ${{ inputs.secrets_key }}
        KIT_NAME: ${{ inputs.kit_name }}
        KIT_VERSION: ${{ steps.version.outputs.new_version }}
        BUILD_ROOT: "build"
      run: |
        echo "::group::Building Genesis Kit ${{ inputs.kit_name }} v${{ steps.version.outputs.new_version }}"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/build-kit.sh
        echo "::endgroup::"

    # Conditionally run testing steps
    - name: Setup debug mode
      if: inputs.debug_mode == 'true'
      id: check-breaking-debug
      shell: bash
      env:
        KIT_NAME: ${{ inputs.kit_name }}
        VERSION: ${{ steps.version.outputs.new_version }}
      run: |
        echo "::group::Setting up debug mode and skipping tests"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/setup-debug-mode.sh
        echo "::endgroup::"

    # RUN SPEC TESTS - Skip in debug mode
    - name: Setup Go for tests
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        GO_VERSION: ${{ inputs.go_version }}
      run: |
        echo "::group::Setting up Go ${{ inputs.go_version }} for tests"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/setup-go.sh
        echo "::endgroup::"

    - name: Run Spec Tests
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        GENESIS_SECRETS_BASE: ${{ inputs.secrets_base }}
        GENESIS_SECRETS_TOKEN: ${{ inputs.secrets_token }}
        GENESIS_SECRETS_KEY: ${{ inputs.secrets_key }}
        KIT_VERSION: ${{ steps.version.outputs.new_version }}
        GINKGO_PARAMS: ${{ inputs.ginkgo_params }}
      run: |
        echo "::group::Running specification tests with Ginkgo ${{ inputs.ginkgo_params }}"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/run-spec-tests.sh
        echo "::endgroup::"

    # SPEC CHANGE CHECK - Skip in debug mode
    - name: Check Specs for breaking changes
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CURRENT_VERSION: ${{ steps.version.outputs.new_version }}
        PREVIOUS_VERSION: ${{ steps.version.outputs.previous_version }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "::group::Checking specifications for breaking changes"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/check-specs.sh
        echo "::endgroup::"

    - name: Check for breaking changes
      if: inputs.debug_mode != 'true'
      id: check-breaking
      shell: bash
      run: |
        echo "::group::Analyzing breaking change report"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/check-breaking-changes.sh
        echo "::endgroup::"

    # INFRASTRUCTURE SETUP FOR DEPLOYMENT - Skip in debug mode
    - name: Setup Infrastructure
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ inputs.gcp_service_account_key }}
        VSPHERE_USERNAME: ${{ inputs.vsphere_username }}
        VSPHERE_PASSWORD: ${{ inputs.vsphere_password }}
        IAAS_PROVIDER: ${{ inputs.iaas_provider }}
      run: |
        echo "::group::Setting up ${{ inputs.iaas_provider }} infrastructure"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/setup-infrastructure.sh
        echo "::endgroup::"
    
    # VAULT SETUP - Skip in debug mode
    - name: Setup Vault
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "::group::Setting up HashiCorp Vault"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/setup-vault.sh
        echo "::endgroup::"

    # DEPLOYMENT TEST - Skip in debug mode
    - name: Deploy and Test
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        DEPLOY_ENV: ${{ inputs.deploy_env }}
        CI_ROOT: "${{ github.workspace }}/git-ci"
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GENESIS_SECRETS_BASE: ${{ inputs.secrets_base }}
        GENESIS_SECRETS_TOKEN: ${{ inputs.secrets_token }}
        GENESIS_SECRETS_KEY: ${{ inputs.secrets_key }}
        GENESIS_STACK_TRACE: "yes"
        BOSH_CLIENT: ${{ inputs.bosh_client }}
        BOSH_CLIENT_SECRET: ${{ inputs.bosh_client_secret }}
        BOSH_ENVIRONMENT: ${{ inputs.bosh_environment }}
        BOSH_CA_CERT: ${{ inputs.bosh_ca_cert }}
        SECRETS_SEED_DATA: ${{ inputs.secrets_seed_data }}
        KIT_VERSION: ${{ steps.version.outputs.new_version }}
        KIT_SHORTNAME: ${{ inputs.kit_name }}
        BUILD_ROOT: "build"
        ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "::group::Deploying and testing to ${{ inputs.deploy_env }}"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/deploy-and-test.sh
        echo "::endgroup::"

    # GENERATE RELEASE NOTES - Simplified in debug mode
    - name: Generate Release Notes
      if: inputs.debug_mode != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        KIT_SHORTNAME: ${{ inputs.kit_name }}
        RELEASE_NOTES_FILE: "release-notes.md"
        VERSION: ${{ steps.version.outputs.new_version }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "::group::Generating release notes for v${{ steps.version.outputs.new_version }}"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/generate-release-notes.sh
        echo "::endgroup::"

    # CREATE PR FOR RELEASE OR MANUAL TRIGGER
    - name: Create Pull Request for Release
      if: steps.check-release-commit.outputs.is_release == 'true' || inputs.debug_mode == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        KIT_NAME: ${{ inputs.kit_name }}
        VERSION: ${{ steps.check-release-commit.outputs.is_release == 'true' && steps.check-release-commit.outputs.version || steps.version.outputs.new_version }}
        RELEASE_BRANCH: ${{ inputs.release_branch }}
        DEBUG_MODE: ${{ inputs.debug_mode }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo "::group::Creating pull request for release v${{ steps.check-release-commit.outputs.is_release == 'true' && steps.check-release-commit.outputs.version || steps.version.outputs.new_version }}"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/create-pr.sh
        echo "::endgroup::"

    - name: Add explanation comment to PR
      if: (steps.check-release-commit.outputs.is_release == 'true' || inputs.debug_mode == 'true')
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        KIT_NAME: ${{ inputs.kit_name }}
        VERSION: ${{ steps.check-release-commit.outputs.is_release == 'true' && steps.check-release-commit.outputs.version || steps.version.outputs.new_version }}
        PR_COMMENT_FILE: "${{ github.action_path }}/docs/pr-comment-template.md"
        DEBUG_MODE: ${{ inputs.debug_mode }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
        RELEASE_BRANCH: ${{ inputs.release_branch }}
      run: |
        echo "::group::Adding explanation comment to pull request"
        chmod -R +x ${{ github.action_path }}/ci/scripts
        ${{ github.action_path }}/ci/scripts/actions/add-pr-comment.sh
        echo "::endgroup::"